import { Providers } from '@/app/provider'
import Layout from '@/src/components/Layout'
import Navbar from '@/src/components/Navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  )
}
